Icons
BenFielmann/Offer-Calculator pull request #2
Opened 2021-09-09 14:52 UTC by BenFielmann

First, I create an assets folder for font and SVG icons
after this, I import the icon SVG's and a new font for better contrasts
and I add a global.css for global variables to work more efficient

#1

2021-09-09 15:38 UTC, phlgr requested changes

2021-09-09 19:18 UTC, BenFielmann commented on src/app/components/assets/Worker.svg
> +</svg>
I'm not really sure if this should be a React Component 
because I want to use this as a background image for the pages
is it necessary to change it to a component or would it be enough to use a PNG of this?

2021-09-09 19:19 UTC, BenFielmann commented on .gitignore
> +src/app/components/QuestionCard
Done😅

2021-09-10 08:34 UTC, BenFielmann commented on src/app/components/assets/Worker.svg
> +</svg>
ok, problem solved I only need the PNG file 😎
as an SVG it would be too complicated to integrate🐱‍👤

2021-09-10 09:34 UTC, merged